name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cmake_generator: Ninja
          - os: windows-latest
            cmake_generator: "Visual Studio 16 2019"
          - os: macos-latest
            cmake_generator: Ninja

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: cmake/setup-cmake@v1
      with:
        cmake-version: '3.21'

    - name: Configure and build
      shell: bash
      run: |
          cmake -S . -B build -G "${{ matrix.cmake_generator }}"
          cmake --build build
